### PR TITLE
[Fix] 修复当调用  repository.go 中 GetXXXValue，类型不一致时的报错

### LINKED ISSUE #215: [BUG] yaml格式namespace取值报错
当我使用yaml格式的namespace时，用`GetConfig`方法获取非string类型的配置时，会报panic

config.yml:

image

取bool类型 panic:

image

取int类型 panic:

image

当我使用`GetConfigCache`方法不报错

image

### PR DESCRIPTION
**Pull request by zouyx**
* Fixed #215 修复当调用  repository.go 中 GetXXXValue，类型不一致时的报错
* 聚合 `client.go` 的 `GetXXXValue` 方法到 `repository.go`

### CODE REVIEW

File: storage/repository.go [hunk 1]
```diff
@@ -182,40 +181,32 @@ func (c *Config) GetSliceValue(key string) []interface{} {
...
+	value := c.getConfigValue(key)
 
-	i, err := strconv.Atoi(value)
-	if err != nil {
-		log.Debug("convert to int fail!error:", err)
+	if value == nil {
 		return defaultValue
 	}
-	return i
+	return value.(int)
```
Comment (nobodyiam) [inline storage/repository.go:189]: I think if there is any error happened in type conversion, we need to log the error and return the default value?

Comment (zouyx) [reply storage/repository.go:189]: I think you are right :)

I had fixed it.

File: client.go [hunk 2]
```diff
@@ -195,89 +193,37 @@ func (c *internalClient) GetApolloConfigCache() agcache.CacheInterface {
 
 //GetValue 获取配置
 func (c *internalClient) GetValue(key string) string {
```
Comment (zouyx) [inline client.go:195]: this method is get default namespace for compatible old version, below as also.

File: client_test.go [hunk 3]
```diff
@@ -49,11 +49,11 @@ func createMockApolloConfig(expireTime int) *internalClient {
 	//string
 	configs["string"] = "value"
 	//int
-	configs["int"] = "1"
```
Comment (zouyx) [inline client_test.go:52]: wrong case ,so change it

**Review by nobodyiam — APPROVED** [review]
LGTM
